name: camfit-getter
app: node@22
options:
  env:
    - name: NODE_ENV
      value: production
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
      value: "true"
    - name: PUPPETEER_EXECUTABLE_PATH
      value: /usr/bin/chromium-browser
  install: npm ci --only=production
  build: echo "No build step required for Node.js project"
  start: npm start
  ports: 3000/http
  resources:
    cpu: 0.25
    memory: 512Mi
  healthcheck:
    path: /health
    port: 3000
    interval: 30s
    timeout: 10s
    retries: 3
  restart: always

